version: "3.1"
services:
  symfony:
    image: ghcr.io/etupdt/ecoride:latest
    container_name: ecoride
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # build:
    #   context: .
    #   args:
    #     POSTGRES_USER: ${POSTGRES_USER}
    #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #     POSTGRES_DB: ${POSTGRES_DB}
    #     POSTGRES_VERSION: ${POSTGRES_VERSION}
    #     POSTGRESQL_SERVER: ${POSTGRESQL_SERVER}
    #     POSTGRESQL_PORT: ${POSTGRESQL_PORT}
    #     MONGO_DB: ${MONGO_DB}
    #     MONGO_URL: ${MONGO_URL}
    env_file: ./env.properties
    restart: always
    ports:
      - "80:8080"
      - "443:9443"
    volumes:
      - /var/www/html
      - /etc/ssl/ecoride:/etc/apache2/ssl/back
      - /etc/apache2/sites-available/back
    depends_on:
      - pgecoride
      - mgecoride

  pgecoride:
    image: postgres:14-alpine
    env_file: ./env.properties
    restart: always
    shm_size: 128mb
    volumes:
      - ecf-ecoride-postgres-prod:/var/lib/postgresql/data
      - ./prod/pgecoride:/docker-entrypoint-initdb.d

  mgecoride:
    image: mongo:8.0.0-rc8-jammy
    env_file: ./env.properties
    restart: always
    volumes:
      - ecf-ecoride-mongodb-prod:/etc/mongo
      - ./prod/mgecoride:/docker-entrypoint-initdb.d

volumes:
  ecf-ecoride-postgres-prod:
  ecf-ecoride-mongodb-prod:
